# Generated by Django 3.2.5 on 2021-07-18 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['cat_name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
