# Generated by Django 3.2.5 on 2021-07-21 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='taken',
            field=models.BooleanField(default=False),
        ),
    ]
